import { Open_Sans, Geist_Mono } from "next/font/google";
import "./globals.css";

const open_sans = Open_Sans({
  variable: "--font-o",
  subsets: ["latin"],
  weight: ['300', '400', '500', '800', '700', '800'],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "My App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${open_sans.variable} ${geistMono.variable}`}>
        {children}
      </body>
    </html>
  );
}
